UI作成 - hikari
tanakahikari-pikka/hoge pull request #10
Opened 2023-09-10 18:31 UTC by tanakahikari-pikka

# 概要
minasehiro さんの課題のUI作成に取り組みました

# 細かな変更点

- 箇条書きで
- UI変更はスクショ添付するとグッド

## スクリーンショット
- Todo一覧表示
![Simulator Screenshot - iPhone 14 - 2023-09-11 at 03 27 06](https://github.com/tanakahikari-pikka/hoge/assets/107383003/8d5b5766-0221-481f-af55-d54caa9b7476)

- ダイアログ
![Simulator Screenshot - iPhone 14 - 2023-09-11 at 03 27 07](https://github.com/tanakahikari-pikka/hoge/assets/107383003/484012e9-edec-4556-981a-7fac5536aef8)

- スナックバー
![Simulator Screenshot - iPhone 14 - 2023-09-11 at 03 27 11](https://github.com/tanakahikari-pikka/hoge/assets/107383003/910656ca-3d89-41bd-9f9e-7d5cdf58f354)

# 影響範囲・懸念点

- プロジェクトファイルなどを荒らしてしまったので、影響範囲を加味しながら差分を取り除いていく

# おこなった動作確認

* [ ] 

# その他

2023-09-12 14:15 UTC, tanakahikari-pikka commented on ios/Runner.xcodeproj/project.pbxproj
> +				2F2C0C1D2AAE2DA700DBD61C /* GoogleService-Info.plist in Resources */,
0274a31e18a10a6059513b8c5fff66dc9409c4bb
上記のコミットで新たにGoogleService-Info.plistを入れ直したときに起こった差分です

2023-09-12 15:47 UTC, minasehiro commented
テスト

2023-09-12 15:49 UTC, minasehiro commented
テスト

2023-09-12 16:33 UTC, minasehiro commented
Broadcast comments to channel

2023-09-14 12:15 UTC, minasehiro requested changes

2023-09-14 12:48 UTC, tanakahikari-pikka commented on ios/Podfile.lock
> +COCOAPODS: 1.12.1
COCOAPODS: 1.11.3
に戻しても動いたので差分は削除しておきました!

2023-09-14 12:51 UTC, tanakahikari-pikka commented on pubspec.lock
> +  flutter: ">=3.7.0"
flutter: ">=3.3.0"
に戻しても動いたので差分は削除しておきました!

2023-09-14 12:51 UTC, tanakahikari-pikka commented on lib/team_development_practice/build_ui/hikari/view/SettingButton.dart
> +// ウィジェットの雛形を作成
copilotに出した指示が残ってました💦すみません!

2023-09-18 06:26 UTC, minasehiro reviewed
最後に1点だけ！

2023-09-18 06:26 UTC, minasehiro commented on ios/Podfile.lock
> +COCOAPODS: 1.12.1
push 漏れですかね...!!

2023-09-21 17:30 UTC, minasehiro approved these changes
適宜ファイルも切り分けられていて、UIもきちんと構成されているのでよいです！！

2023-09-21 17:30 UTC, minasehiro commented
マージします！

2023-09-21 17:30 UTC, merged